### ISSUE TITLE
document issuer

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/signing-service#6]
Context: We need documentation for the MVP issuer, particularly for those wanting to evaluate.

Reproduction: Nothing to reproduce.

Deliverable:  Add to README:

- who this issuer is appropriate for (those who construct own VC)
- how to use DockerHub image, both directly or with Docker Compose, and how to evaluate.  Include a curl to test with.
- how to use with nginx/acme
- config options/requirements
- licence
- errors
- 2 endpoints (issue, status) including arguments, and what each endpoint actually does (e.g., status list entries)
- development instructions including explanation of tests (especially nock.back)
- multi-tenant and how to use
- authentication options, especially for multi-tenant

**Comment by kayaelle** [comment]
@jchartrand - where can we find the documentation? Thanks

**Comment by jchartrand** [comment]
@kayaelle https://github.com/digitalcredentials/signing-service/tree/jc-add-issuer-core
